package pl.com.stoprussia.core.websiteloader;

public enum UrlType {
    DOMAIN_TO_CURRENT_WEBVIEW,
    DOMAIN_TO_ANOTHER_WEBVIEW,
    DOMAIN_TO_OUTSIDE_APP,
    REDIRECTION_TO_MAIN_ACTIVITY,
    URL_TO_CURRENT_WEBVIEW,
    URL_TO_ANOTHER_WEBVIEW,
    URL_TO_OUTSIDE_APP
}
